### PR TITLE
Custom derive for implementing traits

### PR DESCRIPTION
**Pull request by WaDelma**
Starts to address #8.
Not ready for merge as there is still TODOs, just looking for feedback.

### CODE REVIEW

**Comment by WaDelma** [comment]
Apparently .travis.yml needs to be modified because of workspace thing.

**Comment by WaDelma** [comment]
This should be ready for review/merge.

**Comment by WaDelma** [comment]
Note: This doesn't deprecate `macro_rules` based solution or use it for crates own implementations.

**Comment by WaDelma** [comment]
Actually... When trying to use this for vector example I encountered problem: This doesn't support restricting type parameters with traits and I don't know how to add support for that cleanly.

**Comment by sebcrozet** [comment]
Thanks for your work!

I don't know how to allow the user to add its own traits for type parameters but perhaps we could draw take some ideas from serde? Their [documentation](https://serde.rs/attributes.html#container-attributes) states that you can write `#[serde(bound = "T:  MyTrait")]`  so maybe something similar could be done for alga?

**Comment by WaDelma** [comment]
Thanks for giving that idea. I implemented it nearly same way and it works fine.

**Comment by WaDelma** [comment]
Is there still something to do with this/have you had time to review it?

**Comment by sebcrozet** [comment]
Thanks for reminding me! I think this can be merged as-is. There are some limitations regarding user-defined additional type parameters but they can be delayed for now. In particular, if the user specifies:

```rust
#[alga_traits(GroupAbelian(Additive), Where = "Scalar: AbstractField")]
struct Foo<Scalar> {
    …
}
```
, the trait `AbstractField` will be required for `GroupAbelian` **and all its supertraits** to be implemented for `Foo<Scalar>`. It would be useful to be able to say that if `Scalar` implements only, e.g., `AbstractSemigroup` then, `Foo<Scalar>` will only implement `AbstractSemigroup` as well (but not `GroupAbelian`).

I am not sure what would be the most ergonomic way of doing that though.

**Comment by sebcrozet** [comment]
`alga_derive` has been published to crates.io as well!

**Comment by sebcrozet** [comment]
Thanks @WaDelma!

**Pull request merged**
